name: Development

on: push

jobs:
  test:
    name: Test whether all files compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/typst/typst:latest
    steps:
      - name: "list files"
        run: pwd
      - name: "compile SarfTable"
        run: typst compile SarfTable.typ
