name: Development

on: push

jobs:
  test:
    name: Test whether all files compile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/typst/typst:latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "test Fil Conjugation"
        run: typst compile Fi3l/ConjugationTest.typ --root .

      - name: "test Fil Conjugation for Emr and Nehi"
        run: typst compile Fi3l/ConjugationEmrNehiTest.typ --root .

      - name: "test SarfTable"
        run: typst compile Sarf/SarfTableTest.typ --root .
